sudo: true
language: go
services:
  - docker
go:
  - 1.x
script:
  - go fmt $(go list ./... | grep -v vendor) | wc -l | grep 0
  - make test
after_success:
  - if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      sudo ./hack/build-container.sh
      docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
      docker push quay.io/k8scsi/driver-registrar
    fi
